services:
  nginx:
    build: ./requirements/nginx
    restart: always
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    restart: always
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network

  mariadb:
    build: ./requirements/mariadb
    restart: always
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password

volumes:
  wordpress_volume:
  database_volume:

networks:
  inception_network:
    name: Inception
    driver: brige

secrets:
  db_password: 
    file: ../secret/db_password.txt
  db_root_password:
    file: ../secret/db_root_password.txt
